### ISSUE TITLE
验证码问题

### ISSUE THREAD

**Issue by c130xy** [11273/mooc-work-answer#10]
验证码无法打开，提示到根目录打开图片，但是我去根目录找到了这个文件，打开不了

**Comment by 11273** [comment]
你是windows吗

**Comment by c130xy** [comment]
win11

**Comment by c130xy** [comment]
以前只可以刷视频的那个代码的验证码可以打开

**Comment by 11273** [comment]
已提交，拉最新代码

**Comment by c130xy** [comment]
![N1_`TZ23O(E})4HJ%3T3E7](https://user-images.githubusercontent.com/104188963/164648790-b1eb50e4-ba46-41cf-94a9-88f7ffa52635.png)

**Comment by c130xy** [comment]
已经跳过这个课了，但是它还在刷

**Comment by 11273** [comment]
可能是名称不一致，看看是这个课程名吗

**Comment by c130xy** [comment]
![image](https://user-images.githubusercontent.com/104188963/164649406-ff1e7967-0b33-4c6a-ad33-e5a6d6054b55.png)

**Comment by c130xy** [comment]
是这个跳过不了

**Comment by c130xy** [comment]
这个课刷着报错

**Comment by 11273** [comment]
拉一下最新代码，我忘了把刷课的跳过了，只跳过了答题的课程

**Comment by c130xy** [comment]
可以了

**Comment by c130xy** [comment]
![image](https://user-images.githubusercontent.com/104188963/164676676-c5bde64b-68b0-4c92-b01c-606d8b4fc891.png)

**Comment by c130xy** [comment]
还没有开始就结束了

**Comment by 11273** [comment]
你去官网刷一个视频看看会变100%吗，不会的话就是他们服务器出问题了

**Comment by abai2020** [comment]
最新的代码也有验证码打不开的问题

**Comment by 11273** [comment]
可能是他那边服务器有问题，他们官网也卡

**Comment by rainbowAO** [comment]
![image](https://user-images.githubusercontent.com/98279055/164761940-687a7084-78a8-4ac1-a4ff-75117f36990e.png)
