### ISSUE TITLE
新版智慧职教漏视频 非法请求

### ISSUE THREAD

**Issue by zecss** [11273/mooc-work-answer#102]
![QQ截图20230731211605](https://github.com/11273/mooc-work-answer/assets/85402866/3952a630-2c6d-44e3-896b-a8aa722b4438)

![QQ截图20230731212019](https://github.com/11273/mooc-work-answer/assets/85402866/69afe486-8023-493e-b53e-1aa6bd788945)

**Comment by zecss** [comment]
![QQ截图20230731211605](https://github.com/11273/mooc-work-answer/assets/85402866/22e501ef-a2cf-4d91-92ed-f3dd4f7a81dc)

**Comment by 11273** [comment]
什么课程

**Comment by 11273** [comment]
收到

**Comment by RichY0608** [comment]
多久才能修复

**Comment by 11273** [comment]
目前还不太能确定问题
