### ISSUE TITLE
课程过多会显示错误（不刷视频的情况下）

### ISSUE THREAD

**Issue by C315703603** [11273/mooc-work-answer#108]
![9Z5 G(YRS)V(4G%_S_%W0FN](https://github.com/11273/mooc-work-answer/assets/103497700/7c5e4ebc-f492-4dc7-a2cf-a8d9f2d7b4ef)
如图，可能是太快了，在哪里可以调整轮换速度？如果可以的话能选择刷取单独哪个课程吗？目前是根据目录顺序从头开始刷取全部课程，结果就是第二个课程中途断开重新刷取还是从第一个课程开始。

**Comment by 11273** [comment]
这个后面可以考虑，目前还在处理视频的非法请求

**Comment by 11273** [comment]
尝试最新版
