### ISSUE TITLE
视频显示非法请求

### ISSUE THREAD

**Issue by BNLOP** [11273/mooc-work-answer#110]
![image](https://github.com/11273/mooc-work-answer/assets/130216832/2348b4fb-bbff-4ec6-ade3-9733107f1f6a)

**Comment by BNLOP** [comment]
第一次运行运行到了第一章(一共6章)，第二次运行到第五章(第二次显示了填入alicfw，填入了才运行到第五章，然后还是报错)，上面的图是第三次运行结果

**Comment by 11273** [comment]
是什么课程，我测试一下
