### ISSUE TITLE
本次程序运行完成，正常结束。 程序结束，如遇错误请重新运行

### ISSUE THREAD

**Issue by Y-NanLi** [11273/mooc-work-answer#112]
输入账号密码后 程序就结束了 视频是一个都没看
![微信截图_20231025101023](https://github.com/11273/mooc-work-answer/assets/84301190/ab3509d1-da01-40f4-84f2-f9c3d412126d)

**Comment by 11273** [comment]
好的，稍后我测试一下

**Comment by 11273** [comment]
已更新最新版，请再次尝试[最新版下载](https://github.com/11273/mooc-work-answer/releases/tag/v2.1.4)，如有问题请重新打开此Issuse

**Comment by Y-NanLi** [comment]
好的 我试试去



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月2日(周四) 晚上10:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [11273/mooc-work-answer] 本次程序运行完成，正常结束。 程序结束，如遇错误请重新运行 (Issue #112)




 
已更新最新版，请再次尝试最新版下载，如有问题请重新打开此Issuse
