### ISSUE TITLE
源码和软件皆失效，提交bug.

### ISSUE THREAD

**Issue by yqlm159** [11273/mooc-work-answer#113]
![7bb0f61704834f637a5a97ea073ceaa](https://github.com/11273/mooc-work-answer/assets/127719539/f0edd144-4062-4df2-83cf-01578dc06db0)

**Comment by 11273** [comment]
已更新最新版，请再次尝试[最新版下载](https://github.com/11273/mooc-work-answer/releases/tag/v2.1.4)，如有问题请重新打开此Issuse
