### ISSUE TITLE
连接服务器失败

### ISSUE THREAD

**Issue by LHXCxyw** [11273/mooc-work-answer#114]
登录账号到是否自动讨论回复步骤后回车报错，requests.exceptions.ProxyError: HTTPSConnectionPool(host='sso.icve.com.cn', port=443): Max retries exceeded with url: /prod-api/data/userLoginV2 (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)'))))
![image](https://github.com/11273/mooc-work-answer/assets/98746227/f608bac9-b724-4c92-b594-8815e52a2f8a)

**Comment by 11273** [comment]
应该是开了代理，把代理软件关掉或者使用其他电脑运行
