### ISSUE TITLE
获取到课程后就显示运行完毕了，课都没刷

### ISSUE THREAD

**Issue by bujinimeiyandongren** [11273/mooc-work-answer#115]

**Comment by 11273** [comment]
已更新最新版，请再次尝试[最新版下载](https://github.com/11273/mooc-work-answer/releases/tag/v2.1.4)，如有问题请重新打开此Issuse

**Comment by bujinimeiyandongren** [comment]
> 已更新最新版，请再次尝试[最新版下载](https://github.com/11273/mooc-work-answer/releases/tag/v2.1.4)，如有问题请重新打开此Issuse

好的大佬，感谢修复，辛苦了
