### ISSUE TITLE
视频非法请求反馈。刚开始是可以成功的。

### ISSUE THREAD

**Issue by C315703603** [11273/mooc-work-answer#116]
![@LL%DAQVDNY}XZ$18WL~J~F](https://github.com/11273/mooc-work-answer/assets/103497700/bca54d3b-413a-4af6-b3e7-85d403057ea4)
如图，等待大大成功修复这个问题。

**Comment by 11273** [comment]
试试最新版的 [v2.1.5](https://github.com/11273/mooc-work-answer/releases/tag/v2.1.5)
