### ISSUE TITLE
没有生成题库文件呀

### ISSUE THREAD

**Issue by PLA888** [11273/mooc-work-answer#12]
在最新版本中没有看到题库的文件。

**Comment by 11273** [comment]
这个去掉了，现在题目答案都在内存中，答题更快

**Comment by PLA888** [comment]
智慧职教昨晚好像更新了，出现滑块和不能倍速播放



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月23日 00:13 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | 回复：[11273/mooc-work-answer] 没有生成题库文件呀 (Issue #12) |
好的，明白了，谢谢大佬了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月22日 20:53 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [11273/mooc-work-answer] 没有生成题库文件呀 (Issue #12) |

这个去掉了，现在题目答案都在内存中，答题更快

**Comment by 11273** [comment]
现在我这测试可以刷了，应该是暂时去掉了，等他们更新完吧

**Comment by PLA888** [comment]
有人拿你们源代码，二改二开，以此谋利，加入天卡周卡等，逐步成为刷课工具。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月23日 10:49 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [11273/mooc-work-answer] 没有生成题库文件呀 (Issue #12) |

现在我这测试可以刷了，应该是暂时去掉了，等他们更新完吧

**Comment by 11273** [comment]
防不住防不住

**Comment by PLA888** [comment]
哈哈哈哈，删库跑路吧，钱直接让人赚了，我就帮同学刷刷，人家还想加入批量刷课功能



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月28日 12:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [11273/mooc-work-answer] 没有生成题库文件呀 (Issue #12) |

防不住防不住

**Comment by 11273** [comment]
还好职教云的没开源，算了算了😂

**Comment by PLA888** [comment]
这是他们打包好的，有使用限制。
















在 2022-04-28 18:16:41，"HICSTV" ***@***.***> 写道：

我是不会合并那个代码文件，是想让它在一个文件里面，我好打包。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月28日 17:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [11273/mooc-work-answer] 没有生成题库文件呀 (Issue #12) |

还好职教云的没开源，算了算了

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

从网易163邮箱发来的超大附件
新版治教云mooc1.10修复不能指定.zip (106.52M, 2022年5月13日 19:25 到期)
下载
职教云MOOC（单独选择课程唰）.zip (12.47M, 2022年5月13日 19:27 到期)
在线预览 | 下载

**Comment by PLA888** [comment]
听我说两句，最近有些蝼蚁，在github捡了套源码就来装逼了，先免费引流，然后用卡密收费。以下为他们的广告：
群一
天卡 3.88 平均3.88一天
周卡 14.88 平均2.12一天
月卡 29.99 平均0.99一天
永久 88.88 用到我停止维护
群二
1.天卡恢复4周卡恢复19.9
2.后续天卡将每日限量发卡
3.51当日购买周卡2张及以上的赠送等张数天卡，可以2人拼购。(支持分开付款，告知管理你与谁拼即可)例购买两张周卡送2张天卡。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月03日 20:19 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [11273/mooc-work-answer] 没有生成题库文件呀 (Issue #12) |

Closed #12.

**Comment by 11273** [comment]
这么狠，收费这么高，开源也不能添加限制了

**Comment by PLA888** [comment]
这是优化后的版本，各种二开倒卖，太多了




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月04日 11:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [11273/mooc-work-answer] 没有生成题库文件呀 (Issue #12) |

这么狠，收费这么高，开源也不能添加限制了

**Comment by PLA888** [comment]
这是优化后的版本，各种二开倒卖，太多了，竟然卖88



---- 回复的原邮件 ----
发件人 ***@***.***>日期 2022年05月04日 11:08 收件人 ***@***.***>抄送至 ***@***.******@***.***>主题 Re: [11273/mooc-work-answer] 没有生成题库文件呀 (Issue #12)
这么狠，收费这么高，开源也不能添加限制了

**Comment by PLA888** [comment]
好的，明白了，谢谢大佬了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月22日 20:53 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [11273/mooc-work-answer] 没有生成题库文件呀 (Issue #12) |

这个去掉了，现在题目答案都在内存中，答题更快

**Comment by PLA888** [comment]
我是不会合并那个代码文件，是想让它在一个文件里面，我好打包。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月28日 17:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [11273/mooc-work-answer] 没有生成题库文件呀 (Issue #12) |

还好职教云的没开源，算了算了😂
