### ISSUE TITLE
最新版运行问题

### ISSUE THREAD

**Issue by C315703603** [11273/mooc-work-answer#125]
第一次可以完美正常运行，中途退出了重新刷的时候就无法正常刷了

![VG 1M}Z9~F7$5FAES2WI 5J](https://github.com/11273/mooc-work-answer/assets/103497700/9b00b389-aeab-4c31-bb93-8bcec38d55a7)

**Comment by 11273** [comment]
可以看一下日志文件的具体错误信息

**Comment by C315703603** [comment]
大概是从这开始出错的
![2EJ86~PDU@%H0J0GL`FYDV4](https://github.com/11273/mooc-work-answer/assets/103497700/0d9e98cc-8606-4c58-b1a4-f8634126f2cf)
[mooc-work-answer-log_2023-11-22.log](https://github.com/11273/mooc-work-answer/files/13432592/mooc-work-answer-log_2023-11-22.log)

**Comment by 11273** [comment]
重新运行一下， 这个alicfw的cookie要填，现在应该是处理出问题了

**Comment by C315703603** [comment]
确实，重新运行后会弹出填写alicfw，填完后能完美正常运行，谢谢大大
