### ISSUE TITLE
alicfw填入无反应

### ISSUE THREAD

**Issue by LHXCxyw** [11273/mooc-work-answer#126]
![image](https://github.com/11273/mooc-work-answer/assets/98746227/a727e29b-b14a-4f09-a240-4217f84b3792)
在windows2012R2系统中运行时出现alicfw验证，但是填入后程序重复要求填入，没法完成

**Comment by 11273** [comment]
一般是alicfw失效的所有一直不行，尝试浏览器的重新登录呢

**Comment by LHXCxyw** [comment]
> 一般是alicfw故障的所有一直失败，尝试浏览器的重新登录呢

相同的alicfw在本机电脑里能够使用，但是视频刷起来有点慢，所以想放在服务器里运行

**Comment by 11273** [comment]
买的服务器吗，可能阿里的防火墙做了验证防护，试试挂个代理

**Comment by LHXCxyw** [comment]
> 买的服务器吗，可能阿里的防火墙做了验证防护，试试挂个代理

还是不行，服务器是腾讯云的，防火墙也都关闭的

**Comment by 11273** [comment]
可以看一下日志文件，里面是不是有这个
![image](https://github.com/11273/mooc-work-answer/assets/30102887/0bd8ee92-0080-417b-bcec-35c283c548b1)

**Comment by 11273** [comment]
这种就是alicfw的问题了，只能在本地电脑挂机了，一晚上一般就够了

**Comment by LHXCxyw** [comment]
好的

**Comment by LHXCxyw** [comment]
哦哦，明白了，只能在运行的电脑上获取，我是在本地的电脑获取复制到服务器的
