### ISSUE TITLE
大佬 为什么会提示阻挡 是什么情况呢

### ISSUE THREAD

**Issue by luo4xun** [11273/mooc-work-answer#127]
![image](https://github.com/11273/mooc-work-answer/assets/150796881/8b633763-a444-4aab-87b5-bc5164d73bc8
就是这种情况  有的时候 刷着刷着就这样了

**Comment by 11273** [comment]
这个很少碰到，一般是请求太频繁了，没有开多个运行吧，应该过段时间就不会阻挡了
