### ISSUE TITLE
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt 

### ISSUE THREAD

**Issue by 3078455271** [11273/mooc-work-answer#129]
![屏幕截图 2023-12-12 163236](https://github.com/11273/mooc-work-answer/assets/120673965/18d943af-cede-41ca-b1cb-109c3a3b899e)
运行这个命令时报错

**Comment by 11273** [comment]
还是代理或者抓包软件的问题，要关掉

**Comment by 3078455271** [comment]
> 还是代理或者抓包软件的问题，要关掉

 
![屏幕截图 2023-12-12 164243](https://github.com/11273/mooc-work-answer/assets/120673965/f1635dd2-8ec0-44e7-937d-b4a480ee228f)
哥，现在运行完 pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt命令后报这个错误了

**Comment by 11273** [comment]
python 什么版本

**Comment by 3078455271** [comment]
> 运行提示的命令升级一下pip ![image](https://private-user-images.githubusercontent.com/30102887/289798001-a24ef880-9718-4aee-b542-fa532ba99ea4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNzExNTgsIm5iZiI6MTcwMjM3MDg1OCwicGF0aCI6Ii8zMDEwMjg4Ny8yODk3OTgwMDEtYTI0ZWY4ODAtOTcxOC00YWVlLWI1NDItZmE1MzJiYTk5ZWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDA4NDczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZjU5YjBlMTlhYzFlYTQzMDYxYjUyYjNlNzA3YzU1MmQ3YWUyMDE5MzA4MzY3ZjJmOWFhYjJlM2FmNzBmNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y1gj0m89J7U3DxSFBCVn6yWqyIpvBGFVdNbrJmZkM54)

![屏幕截图 2023-12-12 165054](https://github.com/11273/mooc-work-answer/assets/120673965/3646c1e8-683c-42a7-9e78-11b7d6d14d98)
3.8和3.10

**Comment by 3078455271** [comment]
> 升级一下pip再运行pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt

![屏幕截图 2023-12-12 172412](https://github.com/11273/mooc-work-answer/assets/120673965/cbfd3683-4a5d-40c7-b04d-72b5af845e89)
哥，之后出现这个问题了
![屏幕截图 2023-12-12 172542](https://github.com/11273/mooc-work-answer/assets/120673965/be24090f-259e-4992-8c3b-bd6eef633f46)
s'
startwork.py文件的账户和密码，我按照提示改为我自己的账户和小号了

**Comment by 11273** [comment]
没有用单引号或者双引号括起来

**Comment by 3078455271** [comment]
else里的账号要输入吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "11273/mooc-work-answer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月12日(星期二) 下午5:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [11273/mooc-work-answer] pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt  (Issue #129)





 
没有用单引号或者双引号括起来

**Comment by 11273** [comment]
python基础，变量应该用引号
username = "zhangsan"
password = "qwer111111"

**Comment by 11273** [comment]
截图看一下，账号密码注意打码

**Comment by 3078455271** [comment]
> 截图看一下，账号密码注意打码

![Uploading 屏幕截图 2023-12-12 213103.png…]()

**Comment by 3078455271** [comment]
> 截图看一下，账号密码注意打码

![Uploading 屏幕截图 2023-12-12 213103.png…]()

**Comment by 11273** [comment]
现在错误信息是什么呢
