### ISSUE TITLE
@全体成员 04-23：近期暂时无法刷课，都会出异常，原因大概是他们服务器的问题，正常看完课件也不会更新进度，这两天先不要刷课

### ISSUE THREAD

**Issue by 11273** [11273/mooc-work-answer#13]
![image](https://user-images.githubusercontent.com/30102887/164861440-48197e05-93ba-4014-a976-650ef8ef069d.png)

**Comment by ranyong1997** [comment]
收到 over

**Comment by 1466366937** [comment]
大佬，能加个你联系方式不?

**Comment by 11273** [comment]
> 大佬，能加个你联系方式不?

邮箱那有
