### ISSUE TITLE
请求频率超限，请每5分钟提交一次学习数据

### ISSUE THREAD

**Issue by Astighost** [11273/mooc-work-answer#130]
请求频率超限，请每5分钟提交一次学习数据

**Comment by C315703603** [comment]
如题，同种情况，虽然显示在刷，但是实际上课程并没有刷上
![286)$5598Y~OCQ~7`1$ IQ0](https://github.com/11273/mooc-work-answer/assets/103497700/03fe20c6-7fee-490f-95dc-d6cf41799958)

**Comment by 11273** [comment]
收到

**Comment by C315703603** [comment]
![2H5}4(P 4__RR(_@Z0~SJ48](https://github.com/11273/mooc-work-answer/assets/103497700/2c6ffc22-0efd-43c9-93bd-e3c5f2d71d0c)
cong从进度条看可能是平台限制了提交频率，在某段时间平台不收数据而软件还在进行。纯小白希望能有所帮助，辛苦大大了。

**Comment by 11273** [comment]
晚些才有时间打包，急用可代码运行，改此处为120不会出问题（调慢提交速度）
https://github.com/11273/mooc-work-answer/blob/132956387d0aa580ff7f839c4a3aa94e5b5c6124/NewMoocMain/init_mooc.py#L337

**Comment by RichY0608** [comment]
尽快打包一下呢

**Comment by 11273** [comment]
https://github.com/11273/mooc-work-answer/releases/tag/v2.1.6
