### ISSUE TITLE
用2的时候漏的有点多而且不会刷视频

### ISSUE THREAD

**Issue by 1161345164** [11273/mooc-work-answer#136]
日志[mooc-work-answer-log_2023-12-24.log](https://github.com/11273/mooc-work-answer/files/13760854/mooc-work-answer-log_2023-12-24.log)
刷出来的效果
<img width="253" alt="2023-12-24 12-24-20-33" src="https://github.com/11273/mooc-work-answer/assets/154702964/66a43191-57dc-4294-b557-12284df8251e">

**Comment by 1161345164** [comment]
求佬解答

**Comment by 11273** [comment]
视频最近刷不了，还没解决 https://github.com/11273/mooc-work-answer/issues/132

**Comment by 11273** [comment]
https://github.com/11273/mooc-work-answer/releases/tag/v2.1.8
已更新最新版
