### ISSUE TITLE
刷不了

### ISSUE THREAD

**Issue by asdda610** [11273/mooc-work-answer#137]
![image](https://github.com/11273/mooc-work-answer/assets/154819251/35544fca-fd1c-41e9-877d-b40f6123725b)
一直错误

**Comment by 11273** [comment]
旧版还是新版呢

**Comment by asdda610** [comment]
> 旧版还是新版呢

新版

**Comment by 11273** [comment]
看一下日志文件，同级目录下的

**Comment by asdda610** [comment]
[mooc-work-answer-log_2023-12-26.log](https://github.com/11273/mooc-work-answer/files/13771895/mooc-work-answer-log_2023-12-26.log)


> 看一下日志文件，同级目录下的

**Comment by 11273** [comment]
很抱歉，由于您访问的URL有可能对网站造成安全威胁，您的访问被阻断。
目前是这种错误，看看mooc官网能不能登录，应该是频率太快了，或者试试用代理

**Comment by asdda610** [comment]
> 很抱歉，由于您访问的URL有可能对网站造成安全威胁，您的访问被阻断。 目前是这种错误，看看mooc官网能不能登录，应该是频率太快了，或者试试用代理

MOOC可以登，之前还是好好的忽然不能刷了

**Comment by 11273** [comment]
有时间我再复现一下，现在还不会出现，或者可以尝试修改代码运行

**Comment by asdda610** [comment]
> 有时间我再复现一下，现在还不会出现，或者可以尝试修改代码运行

新版与旧版不一样，每次运行只有视频刷不了

**Comment by 11273** [comment]
新版的视频还在处理中

**Comment by asdda610** [comment]
> 新版的视频还在处理中

可以快一点解决吗，感谢

**Comment by 11273** [comment]
先临时处理一下看看能不能用
https://github.com/11273/mooc-work-answer/releases/tag/v2.1.7

**Comment by asdda610** [comment]
> 先临时处理一下看看能不能用 https://github.com/11273/mooc-work-answer/releases/tag/v2.1.7

这个错误Warning: Don’t paste code into the DevTools Console that you don’t understand or haven’t reviewed yourself. This could allow attackers to steal your identity or take control of your computer. Please type ‘allow pasting’ below to allow pasting.

**Comment by asdda610** [comment]
> 先临时处理一下看看能不能用 https://github.com/11273/mooc-work-answer/releases/tag/v2.1.7
错误出来了
[mooc-work-answer-log_2023-12-28.log](https://github.com/11273/mooc-work-answer/files/13787841/mooc-work-answer-log_2023-12-28.log)
![image](https://github.com/11273/mooc-work-answer/assets/154819251/116709ae-01e9-43b0-9461-cb6abee2305b)

**Comment by asdda610** [comment]
> 先临时处理一下看看能不能用 https://github.com/11273/mooc-work-answer/releases/tag/v2.1.7

讨论有点问题
[mooc-work-answer-log_2023-12-28.log](https://github.com/11273/mooc-work-answer/files/13787966/mooc-work-answer-log_2023-12-28.log)
![image](https://github.com/11273/mooc-work-answer/assets/154819251/11d279ec-ca45-4b2a-8103-61c85f086b34)

**Comment by asdda610** [comment]
还漏刷

**Comment by 11273** [comment]
https://github.com/11273/mooc-work-answer/releases/tag/v2.1.8
已更新最新版
