### ISSUE TITLE
关于登录失败的问题

### ISSUE THREAD

**Issue by blg0515** [11273/mooc-work-answer#14]
![image](https://user-images.githubusercontent.com/52337543/164976453-1653c21e-fd01-42f7-aecd-2e902607b8e9.png)

这样的问题是正常的吗‘
’

**Comment by blg0515** [comment]
![image](https://user-images.githubusercontent.com/52337543/164976824-e775a0d4-0c3a-425c-b208-e6483f50d7fa.png)
刷题模式下也是无法登录

**Comment by 11273** [comment]
去官网操作先，估计是要绑定手机

**Comment by blg0515** [comment]
好的，谢谢
