### ISSUE TITLE
希望大佬加入新功能

### ISSUE THREAD

**Issue by cqep** [11273/mooc-work-answer#142]
希望大佬把这个网站（course.icve.com.cn）的刷课功能安排上  主要是也经常再用

**Comment by 11273** [comment]
点进去是首页，是哪个入口呢

**Comment by cqep** [comment]
sso.icve.com.cn  这个是登录入口

**Comment by cqep** [comment]
大佬，什么时候能搞好呢 15号截止了

**Comment by 11273** [comment]
晚两天我适配一下

**Comment by cqep** [comment]
> 晚两天我适配一下

感谢大佬

**Comment by 11273** [comment]
可测试 课堂版 https://github.com/11273/mooc-work-answer/releases/tag/v2.1.9
