### ISSUE TITLE
如果提供大量课程的题库答案，是否可以加入新版mooc的刷题功能

### ISSUE THREAD

**Issue by XXXXBully** [11273/mooc-work-answer#143]
如果提供大量课程的题库答案，是否可以加入新版mooc的刷题功能

**Comment by 11273** [comment]
理论是可以，但是需要另外适配，感觉不是很可靠的方式

**Comment by XXXXBully** [comment]
> 理论是可以，但是需要另外适配，感觉不是很可靠的方式

作者的意思是通过遍历去刷题然后获取官方题库保存在json，再通过获取的题库去答题这种方式会更好对吧

**Comment by 11273** [comment]
是的，之前旧版的是提交考试后会给答案，进行匹配，但是新版的提交后没有答案，用题库的话准确率不高，

**Comment by 11273** [comment]
看看油猴脚本呢，应该有些可以答题的

**Comment by XXXXBully** [comment]
题库不全，分数较低



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月6日(周六) 晚上10:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [11273/mooc-work-answer] 如果提供大量课程的题库答案，是否可以加入新版mooc的刷题功能 (Issue #143)




 
看看油猴脚本呢，应该有些可以答题的

**Comment by RichY0608** [comment]
把题库采集一下呢

**Comment by XXXXBully** [comment]
你这个相当于提供题库没有太大区别，最有效且最好的办法是提权获取官方题库以及答案然后再导入本地json运行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月10日(周三) 晚上10:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [11273/mooc-work-answer] 如果提供大量课程的题库答案，是否可以加入新版mooc的刷题功能 (Issue #143)




 
把题库采集一下呢

**Comment by RichY0608** [comment]
> 是的，之前旧版的是提交考试后会给答案，进行匹配，但是新版的提交后没有答案，用题库的话准确率不高，
大佬  能不能把答题的适配一下 我有课程题库 老师的账号
