### ISSUE TITLE
用户名或密码错误

### ISSUE THREAD

**Issue by yagamilighttuski** [11273/mooc-work-answer#16]
执行python StartWork并填写验证码后显示”用户名或密码错误“，但我确定账号和密码都是没错的，我还手机上退了重新登录试了一下，账号密码无误，请问这是怎么回事？

**Comment by 11273** [comment]
账号密码稍微打下码，截图我看一下你的配置

**Comment by yagamilighttuski** [comment]
> 账号密码稍微打下码，截图我看一下你的配置

![Screenshot_20220428_143440.jpg](https://user-images.githubusercontent.com/78994336/165691777-5fb15aab-a340-4700-83b4-6a9205922f97.jpg)

**Comment by 11273** [comment]
是在这里登录的吗 https://mooc.icve.com.cn/

**Comment by yagamilighttuski** [comment]
不是，是这个https://www.icourse163.org/

**Comment by 11273** [comment]
不是这个mooc奥
