### ISSUE TITLE
这个安全吗大佬，害怕给我号疯了

### ISSUE THREAD

**Issue by WHHHHHHHAT** [11273/mooc-work-answer#164]
谢谢谢谢谢谢

**Comment by 11273** [comment]
用的人挺多的，目前没有反馈被封的

**Comment by WHHHHHHHAT** [comment]
嗯，我在此之前就在用了，谢谢佬，不好意思，给您评论区造成困扰了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年11月16日 22:20 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [11273/mooc-work-answer] 这个安全吗大佬，害怕给我号疯了 (Issue #164) |

用的人挺多的，目前没有反馈被封的
