### ISSUE TITLE
2次运行自动退课bug

### ISSUE THREAD

**Issue by iwbiu** [11273/mooc-work-answer#19]
大号和小号刷课
刷完之后第二次运行会将大号的课程退掉，实测两次都会退课

**Comment by iwbiu** [comment]
第一次刷完不退出程序，再次运行python StartWork.py就会出现这个bug，但是刷完关闭程序，重新打开运行就没事

**Comment by 11273** [comment]
小号退课默认没有打开，暂时先不要打开退课
