### ISSUE TITLE
智慧mooc无法刷题，总是在一个地方出现错误

### ISSUE THREAD

**Issue by shiyaaini** [11273/mooc-work-answer#21]

**Comment by 11273** [comment]
截图看一下

**Comment by shiyaaini** [comment]
![aa2af64b420a76e1a91bf6e7f0dd19b](https://user-images.githubusercontent.com/96780460/166420621-80d10578-adfa-4486-b6d6-d13f19329225.png)

**Comment by a13051967221** [comment]
> 截图看一下

我也一样
