### ISSUE TITLE
提示密码存在隐患，正常登录不会有提示

### ISSUE THREAD

**Issue by ranyong1997** [11273/mooc-work-answer#23]
![bug](https://user-images.githubusercontent.com/67427627/166851073-19312e48-0b69-403b-8ab0-c4061754f716.png)

**Comment by ranyong1997** [comment]
这个初步排查感觉是那边做过校验在新刷的账号第一次能登录成功，后续在登录上去就会提示这个

**Comment by a540641592** [comment]
如何写免验证码登录？或者是自动从手机相册里面弹出验证码图片？（这个脚本只能在电脑里面自动弹出验证码图片）

**Comment by ranyong1997** [comment]
谁让你在手机运行的
