### ISSUE TITLE
python3.10 无法安装运行库

### ISSUE THREAD

**Issue by YANGNIGHT** [11273/mooc-work-answer#24]
![图片](https://user-images.githubusercontent.com/79457406/166940154-5d3c68c4-8c13-4f54-93f6-41f0ce8cf85c.png)

**Comment by 11273** [comment]
可以尝试单独安装运行库，不能装的查看百度具体安装方式或者可以不装，除requests库以外，其他可以选装

**Comment by YANGNIGHT** [comment]
> 可以尝试单独安装运行库，不能装的查看百度具体安装方式或者可以不装，除requests库以外，其他可以选装

好的 我直接用的exe运行的 很好用 差最后一个考试就刷完了  感谢作者大大的程序 哈哈
