### ISSUE TITLE
python 3.10 无法安装 ddddocr，求大佬解决！

### ISSUE THREAD

**Issue by wanghlGitHub** [11273/mooc-work-answer#25]
ERROR: Ignored the following versions that require a different python version: 1.0.8 Requires-Python <3.8; 1.1.0 Requires-Python <3.9; 1.2.0 Requires-Python <3.10; 1.3.0 Requires-Python <3.10; 1.3.1 Requires-Python <3.10; 1.4.0 Requires-Python <3.10; 1.4.1 Requires-Python <3.10; 1.4.2 Requires-Python <3.10; 1.4.3 Requires-Python <3.10
ERROR: Could not find a version that satisfies the requirement ddddocr==1.4.3 (from versions: 1.0.6)
ERROR: No matching distribution found for ddddocr==1.4.3

**Comment by xinyucoder** [comment]
3.6-3.9

**Comment by 11273** [comment]
https://github.com/sml2h3/ddddocr
第三方库，我做不到适配奥，只能降低python版本
