### ISSUE TITLE
🔴近期答题出现阿里云拦截

### ISSUE THREAD

**Issue by 11273** [11273/mooc-work-answer#27]
暂时试试将所以延时调大，近期工作忙没时间解决

**Comment by xinyucoder** [comment]
延时调大没有用，填空题接口的提交值触发拦截了，将str删除大概写成这样就能跑了，我还在测看有没有什么问题，先睡了 明天看结果
![image](https://user-images.githubusercontent.com/36022571/168440961-7cc25b1b-3223-4e19-adfb-0897c5d240ce.png)

**Comment by xinyucoder** [comment]
这么写了之后，填空题答不了了，一个空的也不行，但其他的都正常跑，坐等作者大佬完善

**Comment by xinyucoder** [comment]
已定位问题位置，下午解决

**Comment by xinyucoder** [comment]
问题已解决 WAF对answerJson提交的参数进行了验证 必须由双引号将所提交数据引入才可正常提交 单引号和其他格式均会触发拦截，下面是我写的，经测试没问题
![image](https://user-images.githubusercontent.com/36022571/168460234-f3270a55-655a-45fa-aba6-22b6395ce6c4.png)

**Comment by xinyucoder** [comment]
运行时发现部分填空题带有html标签，加了过滤 如图
在workMain.py中引入import re后 如图更改即可
目前测试无问题
![image](https://user-images.githubusercontent.com/36022571/168461323-24e28584-bd2b-42ad-b63e-43d766880e25.png)
![image](https://user-images.githubusercontent.com/36022571/168461327-f5178feb-4b45-4195-a445-660345eb423f.png)
![image](https://user-images.githubusercontent.com/36022571/168461330-3fac7132-f059-4e88-be7c-7e99948e02e8.png)

**Comment by 11273** [comment]
#28

**Comment by mimikc** [comment]
牛
