### ISSUE TITLE
大佬 我这还是报错 难道是版本不对吗

### ISSUE THREAD

**Issue by YANGNIGHT** [11273/mooc-work-answer#3]
![图片](https://user-images.githubusercontent.com/79457406/161212556-1e120dbd-d655-4f69-9da7-02d256012cf9.png)

**Comment by 11273** [comment]
pip install -r requirements.txt
 试一下这个

**Comment by YANGNIGHT** [comment]
> pip install -r requirements.txt 试一下这个

也还是一样的错误 python版本我也换过好几个了

**Comment by 11273** [comment]
requests 这个库能安装吗

**Comment by YANGNIGHT** [comment]
![图片](https://user-images.githubusercontent.com/79457406/161213803-9578364a-de2b-4daf-90d0-a01caef71e7e.png)
好像还是不行

**Comment by 11273** [comment]
pip install Pillow

**Comment by YANGNIGHT** [comment]
![图片](https://user-images.githubusercontent.com/79457406/161214450-f8b5e095-fb30-4bc7-9deb-c32e3e78ffd9.png)
还是一片红唉

**Comment by 11273** [comment]
现在运行一下代码看是哪个库装不上，给我看看能移出吗

**Comment by YANGNIGHT** [comment]
![图片](https://user-images.githubusercontent.com/79457406/161215084-2aa10517-aee7-4933-92f7-dc7b063d9672.png)
还是这样 好像是这个pillow 我感觉是我电脑出问题了

**Comment by 11273** [comment]
https://www.cnblogs.com/j44p5/p/12564767.html
用这个安装

**Comment by YANGNIGHT** [comment]
![图片](https://user-images.githubusercontent.com/79457406/161215551-80ecb159-3e3b-43d3-90b5-08fefa310f28.png)
我都搜遍方法了试过了 实在没办法才来麻烦的你 嘿嘿 实在没办法就算啦

**Comment by 11273** [comment]
![image](https://user-images.githubusercontent.com/30102887/161216270-63b8c980-40a2-46ec-a46c-4c18834fe125.png)
你是3.6，装Pillow 8.3.2 - 8.4

**Comment by 11273** [comment]
pip install Pillow==8.4.0

**Comment by YANGNIGHT** [comment]
还是一样装不了pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt

**Comment by 11273** [comment]
> 还是一样装不了pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt

不要装这个了，这个里面的版本是9.0

**Comment by YANGNIGHT** [comment]
![图片](https://user-images.githubusercontent.com/79457406/161217959-c7e199ae-c48d-4f19-8cda-f3b8700a8036.png)
又变成了这个 是自动输入验证码的这个ddddocr出问题了吗

**Comment by 11273** [comment]
```python
# -*- coding: utf-8 -*-
# @Time : 2022/3/31 9:34
# @Author : Melon
# @Site : 
# @Note : 
# @File : initMooc.py
# @Software: PyCharm
import time
from io import BytesIO

import requests
from PIL import Image

BASE_URL = 'https://mooc.icve.com.cn'
# 登录
LOGIN_SYSTEM_URL = BASE_URL + '/portal/LoginMooc/loginSystem'


def manual_identify_verify_code(verify_code_content):
    Image.open(BytesIO(verify_code_content)).show()
    return input("请输入验证码：")


def to_url(name, password):
    code_url = "https://mooc.icve.com.cn/portal/LoginMooc/getVerifyCode?ts={}".format(time.time())
    code_result = requests.post(url=code_url)
    code_value = manual_identify_verify_code(code_result.content)

    data = {
        'userName': name,
        'password': password,
        'verifycode': code_value
    }
    result = requests.post(url=LOGIN_SYSTEM_URL, data=data, cookies=code_result.cookies)
    return result


def login(name, password):  # 0.登录
    print('正在登录账号:', name, end="")
    result = to_url(name, password)
    json_result = result.json()
    if json_result['code'] == 1 and json_result['msg'] == "登录成功":
        print("==================== 登陆成功:【" + str(name), json_result['schoolName'],  "】 ====================")
        return result.cookies
    else:
        print("\t\t--->", json_result['msg'])

```

把initMooc.py替换成这个

**Comment by YANGNIGHT** [comment]
![图片](https://user-images.githubusercontent.com/79457406/161221045-9b06d780-c362-4f87-bd5e-e1a7218ba15e.png)
这个 其实我是个小白  不知道账号密码填在哪 这几个地方我都填了一下账号密码试了下 其他的都飞快闪退 只有填在这才有反应 但是他还是显示这个 不填也显示这个

**Comment by 11273** [comment]
StartWork.py
填这里面
# 账号1(大号)
username1 = ""  # 账号
password1 = ""  # 密码
# 账号2(小号)
username2 = ""  # 账号
password2 = ""  # 密码

**Comment by YANGNIGHT** [comment]
哟 能跑了 哈哈哈 万分感谢 麻烦了你一下午的时间
