### ISSUE TITLE
新bug

### ISSUE THREAD

**Issue by blg0515** [11273/mooc-work-answer#30]
![image](https://user-images.githubusercontent.com/52337543/168726352-c5f5e5e0-2ed7-460b-95f9-eb3ca4bbcca1.png)
![image](https://user-images.githubusercontent.com/52337543/168726357-52797722-f91f-4bd2-b2bf-d90b7b8e9f6b.png)
发生异常: ConnectionError
HTTPSConnectionPool(host='mooc.icve.com.cn', port=443): Max retries exceeded with url: /study/learn/statStuProcessCellLogAndTimeLong (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027516322400>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

During handling of the above exception, another exception occurred:

During handling of the above exception, another exception occurred:

  File "E:\mooc-work-answer\MoocMain\lookVideo.py", line 120, in statStuProcessCellLogAndTimeLong
    result = json.loads(requests.post(url=url, data=data, headers=headers, cookies=cookies).text)
  File "E:\mooc-work-answer\MoocMain\lookVideo.py", line 212, in start
    videoTimeTotalLong=0)
  File "E:\mooc-work-answer\StartWork.py", line 65, in <module>
    mook_video.start(user_cookies['ck1'], is_continue_work)

课程网址：https://mooc.icve.com.cn/course.html?cid=JAVHB213767

**Comment by 11273** [comment]
重新运行一下

**Comment by xinyucoder** [comment]
关闭代理 重新运行

**Comment by RQRQ726** [comment]
各位大佬，有没有智慧职教三合一的？
