### ISSUE TITLE
这个脚本不能搞填空题

### ISSUE THREAD

**Issue by a540641592** [11273/mooc-work-answer#31]
![image](https://user-images.githubusercontent.com/85382829/169646159-9710b182-f36a-42e6-b242-992e860a1174.png)

**Comment by 11273** [comment]
已知问题，多个填空暂时不能搞

**Comment by C315703603** [comment]
大大这个修复困难吗？

**Comment by 11273** [comment]
不困难，没什么时间

> 大大这个修复困难吗？
