### ISSUE TITLE
HTML5网页设计技术  测验  项目一测验

### ISSUE THREAD

**Issue by a13051967221** [11273/mooc-work-answer#32]
https://mooc.icve.com.cn/study/myCourse/myCourse.html?courseOpenId=fphvafku0itirjri2ltka

![mmexport1653142602806.png](https://user-images.githubusercontent.com/105981750/169657286-be8a2420-fcea-4602-bcb3-f9342c90d49e.png)![mmexport1653142602806.png](https://user-images.githubusercontent.com/105981750/169657306-cd798b58-1af8-4ae2-bab3-7a63844e98a0.png)

多次重新运行后，每次重试三次依然显示程序异常

**Comment by 11273** [comment]
目前先使用代码运行，等待下一版本打包

**Comment by a13051967221** [comment]
> 目前先使用代码运行，等待下一版本打包

我是纯小白，能简单解释一下吗，用哪个代码😂😂

**Comment by 11273** [comment]
> > 目前先使用代码运行，等待下一版本打包
> 
> 我是纯小白，能简单解释一下吗，用哪个代码😂😂

https://github.com/11273/mooc-work-answer/blob/main/REAEME_RUN.md

**Comment by a13051967221** [comment]
> > > 目前先使用代码运行，等待下一版本打包
> > 
> > 我是纯小白，能简单解释一下吗，用哪个代码😂😂
> 
> https://github.com/11273/mooc-work-answer/blob/main/REAEME_RUN.md

教程里的图片都加载不出来，只能通过更改hosts文件来解决吗？

**Comment by 11273** [comment]
参考 https://github.com/ButterAndButterfly/GithubHost

**Comment by a13051967221** [comment]
> 参考 https://github.com/ButterAndButterfly/GithubHost

好的，谢谢，麻烦您了🌹❤️❤️
