### ISSUE TITLE
登入成功，无法获取到课程

### ISSUE THREAD

**Issue by qq745554175** [11273/mooc-work-answer#38]
登入成功，无法获取到课程

**Comment by 11273** [comment]
是不是结束了的课程

**Comment by qq745554175** [comment]
不是结束的课程 
![image](https://user-images.githubusercontent.com/68127788/176728357-71d7dc01-7277-400b-8cd0-d3ff01ba8698.png)

**Comment by 11273** [comment]
登录一下官网，是不是所有课程都结束了
