### ISSUE TITLE
登录报错 打开验证码失败

### ISSUE THREAD

**Issue by MindSoul123** [11273/mooc-work-answer#39]
![f1a749cd165fc60cb8283d367c26123](https://user-images.githubusercontent.com/59333856/179531452-05c73198-e731-441e-90f9-79196f4bed28.png)

**Comment by 11273** [comment]
试一下用管理员身份运行

**Comment by 11273** [comment]
试试网页直接打开官网，看看正常显示验证码吗

**Comment by MindSoul123** [comment]
emmmm官网是正常的 且可以正常登录上
![9dc3d6aabc3a6fb5db351b6c2ccfac0](https://user-images.githubusercontent.com/59333856/179535680-ec62bad2-c655-41f2-9e6d-06669a8b27e9.jpg)
刚才进入app查看mooc课程 发现无法显示 盲猜可能是职教官方的问题

**Comment by 11273** [comment]
<div class="sub-title">
        <span>我们的系统检测到您的计算机网络中存在异常流量。此网页用于确认这些请求是由您而不是自动程序发出的。<span class="tag">微信扫码继续访问本页面</span></span>
      </div>
      
      
      
      确实，等下一个大版本更新

**Comment by YJ321511** [comment]
还是更新一下吧作者大大，智慧职教mooc出网关了

**Comment by 11273** [comment]
> 希望可以修复一下 查课查不到职教云课程的bug 现在软件只可以查到mooc学院里面的课程 职教云里的课程是不显示的 ，希望下一个版本可以修复一下 可以搞定职教云里面的课程

目前只针对mooc的课程，不涉及职教云，职教云接口时不相同的
