### ISSUE TITLE
求教程呀  小白

### ISSUE THREAD

**Issue by beggerlove** [11273/mooc-work-answer#4]
跪求教程  不会运行呀 dog.jpg

**Comment by 11273** [comment]
就是先有 python环境
导库命令： pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt
输入账号密码后运行命令：python StartWork.py

**Comment by djr334** [comment]
为什么我的pip总是报错

**Comment by beggerlove** [comment]
> 就是先有 python环境
> 导库命令： pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt
> 输入账号密码后运行命令：python StartWork.py

欧克大佬 用vscode运行成功了  完美
