### ISSUE TITLE
G了，平台需要扫码了

### ISSUE THREAD

**Issue by a13051967221** [11273/mooc-work-answer#40]
无法使用了，运行代码闪退
作者最近有更新升级的计划吗

![mmexport1658197240664.png](https://user-images.githubusercontent.com/105981750/179650340-f0799f12-2561-4487-95f8-de499818a987.png)

**Comment by 11273** [comment]
在做，会重新处理刷课

**Comment by YJ321511** [comment]
> 在做，会重新处理刷课

修复好了吗大佬

**Comment by 11273** [comment]
官网的网关又没了

**Comment by YJ321511** [comment]
> 官网的网关又没了

能用了吗

**Comment by 11273** [comment]
我试了是可以用的

**Comment by YJ321511** [comment]
> 我试了是可以用的

大佬又不不行了，不知道咋回事

**Comment by aprivate** [comment]
> 我试了是可以用的

您好，获取网关验证的二维码并弹出图片这部分功能代码可以分享下吗？我可以有偿

**Comment by 11273** [comment]
> 
以后不更新了就开源了
from PIL import Image
Image.open(BytesIO(code_result.content)).show()

**Comment by aprivate** [comment]
> > 
> 
> 以后不更新了就开源了 from PIL import Image Image.open(BytesIO(code_result.content)).show()

您好，请问如何获取网关的二维码呢？这部分py代码可以分享下吗？

**Comment by aprivate** [comment]
> > 
> 
> 以后不更新了就开源了 from PIL import Image Image.open(BytesIO(code_result.content)).show()


> > > 
> > 
> > 
> > 以后不更新了就开源了 from PIL import Image Image.open(BytesIO(code_result.content)).show()
> 
> 您好，请问如何获取网关的二维码呢？这部分py代码可以分享下吗？

大佬，能否分享下从访问到验证扫码到登录的代码，可以加微信有偿；目前在写这部分功能就是卡在扫码这里了；麻烦您了

**Comment by 11273** [comment]
> 大佬，能否分享下从访问到验证扫码到登录的代码，可以加微信有偿；目前在写这部分功能就是卡在扫码这里了；麻烦您了
后面会出分析，无偿

**Comment by YJ321511** [comment]
> > 大佬，能否分享下从访问到验证扫码到登录的代码，可以加微信有偿；目前在写这部分功能就是卡在扫码这里了；麻烦您了
> 
> 后面会出分析，无偿

新版mooc有搞头吗大佬

**Comment by 11273** [comment]
> 新版mooc有搞头吗大佬

应该都差不多吧

**Comment by YJ321511** [comment]
> > 新版mooc有搞头吗大佬
> 
> 应该都差不多吧
有的新版的课程查不到

**Comment by YJ321511** [comment]
> > > 新版mooc有搞头吗大佬
> > 
> > 
> > 应该都差不多吧
> > 有的新版的课程查不到

用你这个写的查不到

**Comment by 11273** [comment]
> > > > 新版mooc有搞头吗大佬
> > > 
> > > 
> > > 应该都差不多吧
> > > 有的新版的课程查不到
> 
> 用你这个写的查不到

按照之前分析的流程可以参考参考 https://www.52pojie.cn/thread-1338063-1-1.html

**Comment by YJ321511** [comment]
> > 新版mooc有搞头吗大佬
> 
> 应该都差不多吧

为啥过期了哇大佬

**Comment by daning66** [comment]
为啥用不了

**Comment by wn488332192** [comment]
显示 “  程序已过测试期间，请获取最新版本！”
在哪里获取最新版呀，大佬
给个地址
