### ISSUE TITLE
🎈近期 MOOC 网关验证扫码

### ISSUE THREAD

**Issue by 11273** [11273/mooc-work-answer#43]
已经快好了

**Comment by aprivate** [comment]
您好，py源码可以分享下吗？

**Comment by 11273** [comment]
> 您好，py源码可以分享下吗？

暂时不开源

**Comment by aprivate** [comment]
网关验证扫码这个能解决吗？

**Comment by 11273** [comment]
https://github.com/11273/mooc-work-answer/releases/tag/v2.0.0-beta

**Comment by aprivate** [comment]
网关验证扫码这个能解决吗？

> > 您好，py源码可以分享下吗？
> 
> 暂时不开源

可以有偿购买可以吗？
