### ISSUE TITLE
代码版的如何搭建环境

### ISSUE THREAD

**Issue by a13051967221** [11273/mooc-work-answer#48]
作者，电脑重置了，搭建环境的教程也没了，求指点

**Comment by 11273** [comment]
![image](https://user-images.githubusercontent.com/30102887/190307295-c434fa2f-3b36-4dac-ab4c-366a0574f8ed.png)

**Comment by a13051967221** [comment]
> ![image](https://user-images.githubusercontent.com/30102887/190307295-c434fa2f-3b36-4dac-ab4c-366a0574f8ed.png)
> 

万分感谢
