### ISSUE TITLE
为什么我pip总是报错

### ISSUE THREAD

**Issue by djr334** [11273/mooc-work-answer#5]

**Comment by 11273** [comment]
截图看一下

**Comment by djr334** [comment]
![image](https://user-images.githubusercontent.com/103511737/162975372-0d2b4db1-5c0a-4a2a-a82e-a09be58aa166.png)

**Comment by 11273** [comment]
不是进入python命令行安装，是直接cmd窗口安装，不要输入python

**Comment by djr334** [comment]
然后直接输入账户密码吗

**Comment by 11273** [comment]
打开 StartWork.py 这个文件，填好账号密码，然后cmd运行命令： python StartWork.py
