### ISSUE TITLE
pip安装成功，双击StartWork.py就闪退  小白！

### ISSUE THREAD

**Issue by linbiao666** [11273/mooc-work-answer#6]
![V@~2$@KW@O7`6U~DA2ZD(G9](https://user-images.githubusercontent.com/103568980/163158220-a7418dfc-5362-4d4e-a85a-144b74c50927.png)

**Comment by 11273** [comment]
你要在这个项目目录下运行，不是随便一个地方都能运行

**Comment by 11273** [comment]
你要在这个项目目录下运行，不是随便一个地方都能运行

**Comment by linbiao666** [comment]
不会填了，账号密码填哪里？
![QZ(6 P$LY18W30F)5QW(%69](https://user-images.githubusercontent.com/103568980/163163775-358b3d17-0574-4415-bb81-090fefd4a25d.png)

**Comment by 11273** [comment]
你用记事本什么的打开这个 StartWork.py  你就能发现新大陆

**Comment by linbiao666** [comment]
大佬，我研究了一个小时还是没研究透，能不能出一个操作视频
![78{ 1L7KZOFMF)}J~7ZO%2C](https://user-images.githubusercontent.com/103568980/163175732-97c9e711-3229-4ccb-80a7-023b0ae6544d.png)
？

**Comment by linbiao666** [comment]
大佬能给一个职教云小号？作业要15号交了，没新的手机卡了

**Comment by 11273** [comment]
号：ZS2022T
密：@ZS2022T

**Comment by linbiao666** [comment]
大佬，小号在哪添加网课？![Z QDBQRJLMNQHD}GIZOYV%Y](https://user-images.githubusercontent.com/103568980/163182675-1a4d30b3-8c19-40ef-adf3-b59ecc9c384c.png)

**Comment by linbiao666** [comment]
我用网页登陆就强制要填邀请码

**Comment by 11273** [comment]
只支持 https://mooc.icve.com.cn/
不支持 https://zjy2.icve.com.cn/

README.md文件内有说明，请先看这个
