### ISSUE TITLE
智慧职教无法登录

### ISSUE THREAD

**Issue by wpgez** [11273/mooc-work-answer#61]
![图片](https://user-images.githubusercontent.com/68837615/207058519-df31da60-a512-4b8b-b5bd-503daedecb82.png)
智慧职教无法登录，登录页面有变，我的邮箱962822092@qq.com

**Comment by 11273** [comment]
新版的还在适配中

**Comment by RichY0608** [comment]
验证码在哪看

**Comment by 11273** [comment]
> 验证码在哪看

新版滑动验证码还在解决中
