### ISSUE TITLE
为啥会显示未绑定手机号啊，我绑定了还是报错

### ISSUE THREAD

**Issue by yqlm159** [11273/mooc-work-answer#73]
![屏幕截图 2023-03-13 141300](https://user-images.githubusercontent.com/127719539/224622153-6d38ddee-f1f2-420f-bef0-a3383976b19e.jpg)

**Comment by 11273** [comment]
在网页上登录看看有没有提示

**Comment by yqlm159** [comment]
![5a69b05959a4a9b3199217da893d8ac](https://user-images.githubusercontent.com/127719539/225278069-be29a83f-bc27-41b7-b802-8d28f8a46a8d.png)
大佬这个是什么情况啊
![f9f2f15cd38b08087e4301d9f5b919d](https://user-images.githubusercontent.com/127719539/225278318-8a022b29-1f3d-4f53-a32e-f7180035274c.png)
这个pad安装一直报错，其他的能安
求大佬看看

**Comment by 11273** [comment]
pip install crypto
是这个命令不能安装吗

**Comment by 11273** [comment]
也有可能是你的python版本太高
>https://pypi.org/project/crypto/
> Tested in cPython 2.7.x, 3.4.x, and pypy 2.6.x (Python version 2.7.9)

**Comment by yqlm159** [comment]
我换个低版本的试试

**Comment by yqlm159** [comment]
![image](https://user-images.githubusercontent.com/127719539/225298604-7617d1a0-3d13-4846-b2ce-17beb7768a08.png)
我换了3.7显示安装成功了，还是不行啊报错

**Comment by yqlm159** [comment]
3.6也不行，这是咱回事啊

**Comment by yqlm159** [comment]
![image](https://user-images.githubusercontent.com/127719539/225303774-12d5076d-6c72-43e7-8ed6-7341d14bcc69.png)
库虽然标红但是不报错，运行之后是正则那行代码错了，您看看

**Comment by 11273** [comment]
在这登录一下，可能是你登录太多了，出现滑块验证码，现在没有处理滑块的<https://sso.icve.com.cn/sso/auth?mode=simple&source=2&redirect=https://mooc.icve.com.cn>

**Comment by yqlm159** [comment]
一句 pip install pycryptodome 解决了.....，还是感谢大佬，虽然没办法刷百分百的课但大部分都能刷
