### ISSUE TITLE
你好，请问一下这个报错，该怎么解决。（新版登录）

### ISSUE THREAD

**Issue by zhentianlilinai** [11273/mooc-work-answer#75]
![8X8`30(E 1T2)`QFT @712](https://user-images.githubusercontent.com/129142385/228129632-7e2d705e-ff5f-4ef3-81c3-74b6776292be.png)

**Comment by 11273** [comment]
python是什么版本

**Comment by zhentianlilinai** [comment]
3.6.0

**Comment by 11273** [comment]
要python3.7的环境

**Comment by zhentianlilinai** [comment]
已经更换3.7了，但还是出现报错。
![5{4$AM3UNYF%WHIX912DZW6](https://user-images.githubusercontent.com/129142385/228152890-32bdbaa6-0aa8-4d10-acb6-89840a5ddfa0.png)

**Comment by 11273** [comment]
执行这个命令
 `pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r pycryptodome==3.17`

**Comment by zhentianlilinai** [comment]
感谢大佬！！它运行成功了！！
