### ISSUE TITLE
新版使用

### ISSUE THREAD

**Issue by C315703603** [11273/mooc-work-answer#76]
大佬，求刷新版的大致使用方法

**Comment by 11273** [comment]
打开 NewMoocMain/init_mooc.py 中 auth(session, "此处填写登录账号", "此处填写登录密码") 填写账号密码即可运行(仅需运行 init_mooc.py 文件)

**Comment by RichY0608** [comment]
验证码用什么打开

**Comment by 11273** [comment]
> 验证码用什么打开

旧版的会自动弹出

**Comment by RichY0608** [comment]
我都收到这个  请前往该项目根目录找到并打开 verify_code.jpg 后输入验证码!!!   用什么打开这个歌 jpg

**Comment by 11273** [comment]
用自带的图片查看器，如果显示图片已损坏什么的，就是打不开有问题，要进一下官网登录看看

**Comment by RichY0608** [comment]
网站上可以登上去  现在就是没法打开这个jpg

**Comment by 11273** [comment]
这个要晚点解决，只在部分人那会出现这种，大部分是可以正常弹出的，所以不太好定位问题

**Comment by RichY0608** [comment]
要么就是密码不对 要么就是验证码超时
