### ISSUE TITLE
新版运行错误from MoocMain.log import Logger ModuleNotFoundError: No module named 'MoocMain'

### ISSUE THREAD

**Issue by raozihan** [11273/mooc-work-answer#81]
D:\Tools\mooc-work-answer-main\NewMoocMain>python init_mooc.py
Traceback (most recent call last):
  File "D:\Tools\mooc-work-answer-main\NewMoocMain\init_mooc.py", line 16, in <module>
    from MoocMain.log import Logger
ModuleNotFoundError: No module named 'MoocMain'

**Comment by raozihan** [comment]
![image](https://user-images.githubusercontent.com/53346252/230333416-7100a46b-f03e-4ee1-8009-91553d4f3222.png)

**Comment by raozihan** [comment]
> ![图像](https://user-images.githubusercontent.com/53346252/230333416-7100a46b-f03e-4ee1-8009-91553d4f3222.png)

出现了新的报错

**Comment by 11273** [comment]
这个不是错误，是正常的日志
