### ISSUE TITLE
新版怎么登陆不上去

### ISSUE THREAD

**Issue by ZRRWJ** [11273/mooc-work-answer#82]
新版mooc登录不上去.显示密码错误

**Comment by 11273** [comment]
看看网页可不可以登录

**Comment by ZRRWJ** [comment]
网页可以

**Comment by 11273** [comment]
是修改这个地方登录的还是exe文件登录的呢
[https://github.com/11273/mooc-work-answer/blob/63608fb1ec63005a4e24c199530fc8f2b975221c/NewMoocMain/init_mooc.py#L271](url)
对应的登录页面是：[https://sso.icve.com.cn/sso/auth](url)

**Comment by ZRRWJ** [comment]
exe文件登陆的

**Comment by ZRRWJ** [comment]
旧版可以登上去，新版显示密码错误，去新版官网可以登录上去

**Comment by 11273** [comment]
新版没有打包到exe，要用代码运行

**Comment by ZRRWJ** [comment]
好的吧，谢谢啦，什么时候打包到exe啊

**Comment by 11273** [comment]
最近没什么时间，要晚一点打包exe的

**Comment by ZRRWJ** [comment]
ok，感谢大佬
