### ISSUE TITLE
mooc.icve.com.cn还能刷吗

### ISSUE THREAD

**Issue by LHXCxyw** [11273/mooc-work-answer#83]
我这用新版登录会提示账号或密码错误
去https://mooc.icve.com.cn/
网页能登录进去，是这个版本的不能刷了吗

**Comment by 11273** [comment]
新版要运行代码
新版目前临时测试使用，暂不稳定，打开 NewMoocMain/init_mooc.py 中 auth(session, "此处填写登录账号", "此处填写登录密码") 填写账号密码即可运行(仅需运行 init_mooc.py 文件)
