### ISSUE TITLE
新版这是什么情况

### ISSUE THREAD

**Issue by wjb758521** [11273/mooc-work-answer#84]
<img width="736" alt="Snipaste_2023-04-19_00-27-58" src="https://user-images.githubusercontent.com/113767986/232845560-e38d7676-3348-4b71-8ce7-c808b03c92c1.png">

**Comment by BaitianXI** [comment]
我也遇到了这个问题

**Comment by 11273** [comment]
项目打开方式的问题

**Comment by wjb758521** [comment]
那该怎么办呢

**Comment by 11273** [comment]
![image](https://user-images.githubusercontent.com/30102887/236359725-8b713311-42df-4d8e-9f35-39c0d9ec14d2.png)
需要这种结构再运行奥

**Comment by NRSMDLFSF** [comment]
> ![image](https://user-images.githubusercontent.com/30102887/236359725-8b713311-42df-4d8e-9f35-39c0d9ec14d2.png) 需要这种结构再运行奥
<img width="1280" alt="Snipaste_2023-05-07_20-59-55" src="https://user-images.githubusercontent.com/94678725/236679133-6212d707-55e5-4897-a4df-f64e7bc39660.png">
老大我是这种结构但还是运行失败哎 请教老大

**Comment by 11273** [comment]
在 `init_mooc.py` 这个文件代码那右键，选择 `run init_mooc.py`

**Comment by 11273** [comment]
打包了exe，可以试试

**Comment by NRSMDLFSF** [comment]
> 打包了exe，可以试试

OK 感恩老大。开心每一天。
