### ISSUE TITLE
大佬，新版的mooc可以打包个exe吗?

### ISSUE THREAD

**Issue by ZRRWJ** [11273/mooc-work-answer#86]
大佬，新版的mooc可以打包个exe吗？

**Comment by 11273** [comment]
要晚点奥，主要是新版不稳定

**Comment by ZRRWJ** [comment]
大概得什么时候啊，有几门课马上结课了🥲🥲🥲

**Comment by 11273** [comment]
打包了，可以下载试试 https://github.com/11273/mooc-work-answer/releases/tag/v2.0.2
