### ISSUE TITLE
密码错误

### ISSUE THREAD

**Issue by 343dsadaadw** [11273/mooc-work-answer#87]
我下载最新版2.1exe那个，我输入正确的账号密码还是显示 登陆失败: 用户名或密码错误

**Comment by 11273** [comment]
能在旧版https://mooc-old.icve.com.cn 能登录，就可以登录。新版可以登录，旧版也不一定可以登录

**Comment by 343dsadaadw** [comment]
T_T
***@***.***

**Comment by 343dsadaadw** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "11273/mooc-work-answer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月8日(星期一) 中午12:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [11273/mooc-work-answer] 密码错误 (Issue #87)





 
Closed #87 as completed.
