### ISSUE TITLE
大佬填空题做不了

### ISSUE THREAD

**Issue by rainbowAO** [11273/mooc-work-answer#9]

**Comment by 11273** [comment]
https://github.com/11273/mooc-work-answer/blob/main/README.md?plain=1#L15-L19

**Comment by rainbowAO** [comment]
有点笨，不会在控制台找答案

**Comment by rainbowAO** [comment]
![image](https://user-images.githubusercontent.com/98279055/163949227-caf51200-b083-4f16-90c8-f0fb8daf5749.png)

**Comment by rainbowAO** [comment]
![微信截图_20220419152840](https://user-images.githubusercontent.com/98279055/163949328-9c71a18a-4723-4e62-887a-3adb51247c01.png)

**Comment by rainbowAO** [comment]
控制台里全是这些东西

**Comment by 11273** [comment]
不是这种控制台，是你运行我这个程序的时候，我会输出这些答案，你注意查看

**Comment by rainbowAO** [comment]
okok看到了，谢谢大佬辛苦了

**Comment by rainbowAO** [comment]
![image](https://user-images.githubusercontent.com/98279055/164762143-fa380d14-cb97-4d8c-bce9-d7700d50eb20.png)

大佬好像抓取过来的验证码出现了些问题打不开了

**Comment by rainbowAO** [comment]
jpg其他文件电脑是可以照常打开的确定不是文件的格式问题

**Comment by rainbowAO** [comment]
我用word文档打开了不过

![image](https://user-images.githubusercontent.com/98279055/164763260-99fd0186-8da9-414a-a8ad-e6321821c9d5.png)

**Comment by rainbowAO** [comment]
似乎被墙了

**Comment by rainbowAO** [comment]
![image](https://user-images.githubusercontent.com/98279055/164763493-281d21e5-c7b5-443d-9c85-bbd30a12470e.png)

**Comment by rainbowAO** [comment]
![image](https://user-images.githubusercontent.com/98279055/164763531-9eb358dc-10b4-4035-b8ea-f6bcd4d2cde2.png)

**Comment by 11273** [comment]
拉最新代码，昨天他们服务器估计有问题，先不急

**Comment by rainbowAO** [comment]
> 拉最新代码，昨天他们服务器估计有问题，先不急

好的问题解决了，大佬幸苦了

**Comment by rainbowAO** [comment]
> 拉最新代码，昨天他们服务器估计有问题，先不急

![image](https://user-images.githubusercontent.com/98279055/164860732-5f3b0f3b-241a-4812-8f1a-8e5dd2b96119.png)

最新代码好像，开小号直接报错，不开小号就提示我课程完成但实际没完成

**Comment by 11273** [comment]
目前还是他们服务器的问题，不用管
