### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by LevDeris** [11273/mooc-work-answer#92]
新版登录成功后提升这个然后就程序结束了{"code":200,"msg":"ok","data":"747a0f3a-63fe-4b13-a26d-dba76b9f9b4e","sign":null}
{'loginId': '522423200104259655', 'data': [], 'totalPage': '0', 'errorCode': '200', 'newSiteCode': 'zhzj', 'totalCount': '0', 'errorMsg': ''}。
/
/

**Comment by 11273** [comment]
官网能正常登录吗 https://sso.icve.com.cn/sso/auth?mode=simple&source=2&redirect=https://mooc.icve.com.cn

**Comment by C315703603** [comment]
可以看下课程是否加入学习，我有次没加入会显示这个。
