### ISSUE TITLE
获取alicfw

### ISSUE THREAD

**Issue by C315703603** [11273/mooc-work-answer#93]
![K3$4P04NBHPPS}ISOUHT(}M](https://github.com/11273/mooc-work-answer/assets/103497700/db0ca072-15ef-4427-b87c-6a528c2572c3)
求问获取不到alicfw,这种情况应该如何处理。

**Comment by 11273** [comment]
都退出登录再重新登录一下

**Comment by wangzb12358** [comment]
我重新登录也依旧无法获取alicfw

**Comment by C315703603** [comment]
> 都退出登录再重新登录一下

依旧如之前图片，无法获取到alicfw

**Comment by wangzb12358** [comment]
> Reference
我也和你一样

**Comment by 11273** [comment]
方便给个账号吗

**Comment by wangzb12358** [comment]
> 方便给个账号吗

17639522607
1235460.aW

**Comment by C315703603** [comment]
今日反馈，可以获取到alicfw。但是无效
![{H7Z WFR_VNE1 P{{8@JQ](https://github.com/11273/mooc-work-answer/assets/103497700/26830340-4cb8-4c30-b099-76dc8c7360d1)
![%ZGC3~G 6T(EOB3WIW%YBV](https://github.com/11273/mooc-work-answer/assets/103497700/97802e8d-b0e9-40c7-8b46-18046df85b52)
![0AW@1ZNOG7 V HV_W{X}HII](https://github.com/11273/mooc-work-answer/assets/103497700/e413e10f-06e7-4e49-a71b-fc39a864179b)
如上，根据日志对打包软件重登，在学习平台也重新登录，获取的alicfw依旧不变，同样还是如上图无效。

**Comment by 11273** [comment]
其实是有时候不会出alicfw，获取到的也是之前的，需要重新获取看看是哪里拦截的

**Comment by yqlm159** [comment]
昨天下午还获取到了alicfw，刷了几个账号，然后到五个账号的时候就不行了，再获取就是空的了null。

**Comment by 11273** [comment]
我的账号没有出现，不太好调，要有测试账号才行

> 昨天下午还获取到了alicfw，刷了几个账号，然后到五个账号的时候就不行了，再获取就是空的了null。

**Comment by yqlm159** [comment]
用户：admin0
密码：Sdwcvc2021^*
这个账号我没用，就加了一门课，您可以拿去试试也是获取不到

**Comment by yqlm159** [comment]
> 昨天下午还获取到了alicfw，刷了几个账号，然后到五个账号的时候就不行了，再获取就是空的了null。

1

**Comment by 11273** [comment]
ok， 我试试

**Comment by 11273** [comment]
@C315703603  @yqlm159  @Loaodoina  可以试一下 https://github.com/11273/mooc-work-answer/releases/tag/v2.1.1

**Comment by Loaodoina** [comment]
能用了，感谢大佬

**Comment by yqlm159** [comment]
> @C315703603 @yqlm159 @Loaodoina 可以试一下 https://github.com/11273/mooc-work-answer/releases/tag/v2.1.1

现在可以了，感谢

**Comment by luoli2287123192** [comment]
怎么获取alicfw 有没有大佬教一下的 拜托拜托

**Comment by Loaodoina** [comment]
> 怎么获取alicfw 有没有大佬教一下的 拜托拜托

现在程序已经不用获取alicfw了吧
